In [1]:
import numpy as np
from scipy.linalg import toeplitz
from scipy.sparse.linalg import cg
from numpy.linalg import norm, cond

A = np.arrayH6 = np.array([
    [1, 1/2, 1/3, 1/4, 1/5, 1/6],
    [1/2, 1/3, 1/4, 1/5, 1/6, 1/7],
    [1/3, 1/4, 1/5, 1/6, 1/7, 1/8],
    [1/4, 1/5, 1/6, 1/7, 1/8, 1/9],
    [1/5, 1/6, 1/7, 1/8, 1/9, 1/10],
    [1/6, 1/7, 1/8, 1/9, 1/10, 1/11]
])

condition_number = cond(A, p=np.inf)
print(f"Число обумовленості матриці A: {condition_number}")
if round(condition_number) > 1:
    print("Матриця погано обумовлена.")
else:
    print("Матриця добре обумовлена.")



Число обумовленості матриці A: 29070279.007664092
Матриця погано обумовлена.


In [26]:
n = A.shape[0]
x_real = np.ones(n)
print(x_real)
b1 = A @ x_real
print(b1)

def conjugate_gradient_method(A, b, x0=None, tol=1e-8, max_iter=1000):
    n_iters = [0]
    def callback(xk):
        n_iters[0] += 1
    
    if x0 is None:
        x0 = np.zeros(len(b))
    x, info = cg(A, b, x0=x0, rtol=tol, maxiter=max_iter, callback=callback)
    if info == 0:
        print(f"Метод спряжених градієнтів зійшовся за {n_iters[0]} ітерацій.")
    else:
        print("Метод спряжених градієнтів не зійшовся.")
    return x

def relaxation_method(A, b, omega=1.25, tol=1e-8, max_iter=1000000):
    n = len(b)
    x = np.zeros(n)
    for iteration in range(max_iter):
        x_old = x.copy()
        for i in range(n):
            sigma = sum(A[i, j] * x[j] for j in range(n) if j != i)
            x[i] = (1 - omega) * x[i] + (omega / A[i, i]) * (b[i] - sigma)
        if norm(x - x_old, ord=2) < tol:
            print(f"Метод релаксації зійшовся за {iteration+1} ітерацій.")
            return x
    print("Метод релаксації не зійшовся.")
    return x

x_cg_b1 = conjugate_gradient_method(A, b1)
x_relax_b1 = relaxation_method(A, b1)

print("Розв'язок для b1 (метод спряжених градієнтів):", x_cg_b1)
print("Розв'язок для b1 (метод релаксації):", x_relax_b1)


[1. 1. 1. 1. 1. 1.]
[2.45       1.59285714 1.21785714 0.99563492 0.84563492 0.73654401]
Метод спряжених градієнтів зійшовся за 6 ітерацій.
Метод релаксації зійшовся за 582782 ітерацій.
Розв'язок для b1 (метод спряжених градієнтів): [1.00000116 0.99996689 1.00022378 0.99941847 1.00064135 0.99974748]
Розв'язок для b1 (метод релаксації): [1.0000047  0.99986983 1.00086324 0.99778725 1.00241518 0.99905676]


In [27]:
b2 = b1 + 0.01
b3 = b1  + 0.0055
print(f"b1 and b2 norm value: {np.linalg.norm(b2 - b1, ord=2) * 100}")
print(f"b1 and b3 norm value: {np.linalg.norm(b1 - b3, ord=2) * 100}")

b1 and b2 norm value: 2.449489742783171
b1 and b3 norm value: 1.3472193585307537


In [28]:

x_cg_b2 = conjugate_gradient_method(A, b2)
x_relax_b2 = relaxation_method(A, b2)

x_cg_b3 = conjugate_gradient_method(A, b3)
x_relax_b3 = relaxation_method(A, b3)

print("Error comparison for relaxation method x:")
print("Percentage Error for solving using original vector b", np.linalg.norm(x_relax_b1 - x_real) * 100)

print("Percentage Error for solving using vector b1 (b + 0.01):", np.linalg.norm(x_relax_b2 - x_real) * 100)

print("Percentage Error for solving using vector b1 (b + 0.0055):", np.linalg.norm(x_relax_b3 - x_real) * 100)


Метод спряжених градієнтів зійшовся за 8 ітерацій.
Метод релаксації не зійшовся.
Метод спряжених градієнтів зійшовся за 8 ітерацій.
Метод релаксації не зійшовся.
Error comparison for relaxation method x:
Percentage Error for solving using original vector b 0.35186923236782525
Percentage Error for solving using vector b1 (b + 0.01): 8170.718761624336
Percentage Error for solving using vector b1 (b + 0.0055): 4493.847197084842


In [29]:
print("Error comparison for conjugate gradient method x:")
print("Percentage Error for solving using original vector b", np.linalg.norm(x_cg_b1 - x_real) * 100)

print("Percentage Error for solving using vector b1 (b + 0.01):", np.linalg.norm(x_cg_b2 - x_real) * 100)

print("Percentage Error for solving using vector b1 (b + 0.0055):", np.linalg.norm(x_cg_b3 - x_real) * 100)

Error comparison for conjugate gradient method x:
Percentage Error for solving using original vector b 0.09297599820824355
Percentage Error for solving using vector b1 (b + 0.01): 8697.247841176102
Percentage Error for solving using vector b1 (b + 0.0055): 4783.48631278829


In [61]:
import numpy as np

# Define the matrix A
A = np.array([
    [2, 1, 4, -1],
    [3, -2, 1, 0],
    [5, 1, -3, 2],
    [-1, 3, 3, -1]
])

# Compute A^T A
AtA = np.transpose(A) @ A

# Compute eigenvalues of A^T A
eigenvalues = np.linalg.eigvals(AtA)
non_zero_eig = [eig for eig in eigenvalues if eig > 1e-10]
non_zero_eig_prod = np.prod(non_zero_eig)
print("Eigenvalues:", eigenvalues)
print("Non-zero eigenvalues:", non_zero_eig)
print("Product of non-zero eigenvalues:", non_zero_eig_prod)

# Define x_real
n = A.shape[0]
x_real = np.ones(n)
for i in range(n):
    x_real[i] = np.float32(i+1)
print("x_real:", x_real)

# Compute b1
b1 = A @ x_real
AtB = np.transpose(A) @ b1
print("b1:", b1)
print("A^T b1:", AtB)

# Solution using np.linalg.solve for comparison
x_computed = np.linalg.solve(A, b1)
print("Computed x:", x_computed)

# Solution using the updated method
x_values = []
for i in range(4):
    A_new = AtA.copy()
    A_new[:, i] = AtB
    print(f"A^T * A after {i+1}th column change: \n {A_new}")

    det_values = []
    cur_range = [j for j in range(4) if j != i]
    for idx in cur_range:
        A_subloop = np.delete(A_new, idx, axis=0)
        A_subloop = np.delete(A_subloop, idx, axis=1)
        print(f"\n A^T * A after column {idx + 1}th and row {idx + 1}th deletion: \n {A_subloop}")
        current_det = np.linalg.det(A_subloop)
        print(f"Determinant value for current component: {current_det}")
        det_values.append(current_det)
    x_values.append(np.sum(np.array(det_values)) / non_zero_eig_prod)

print("x_values:", x_values)
print("A^T A x_values:", AtA @ x_values)
print("relative euclidean norm = %.14f" % (np.linalg.norm((AtA @ x_values) - AtB) / np.linalg.norm(AtB)))


Eigenvalues: [ 5.10477598e+01  3.13895815e+01 -1.11881843e-15  1.25626587e+01]
Non-zero eigenvalues: [51.04775977798845, 31.389581519597307, 12.562658702414323]
Product of non-zero eigenvalues: 20130.000000000044
x_real: [1. 2. 3. 4.]
b1: [12.  2.  6. 10.]
A^T b1: [ 50.  44.  62. -10.]
Computed x: [1. 2. 3. 4.]
A^T * A after 1th column change: 
 [[ 50  -2  -7   9]
 [ 44  15   8  -2]
 [ 62   8  35 -13]
 [-10  -2 -13   6]]

 A^T * A after column 2th and row 2th deletion: 
 [[ 50  -7   9]
 [ 62  35 -13]
 [-10 -13   6]]
Determinant value for current component: -360.0000000000023

 A^T * A after column 3th and row 3th deletion: 
 [[ 50  -2   9]
 [ 44  15  -2]
 [-10  -2   6]]
Determinant value for current component: 5345.999999999995

 A^T * A after column 4th and row 4th deletion: 
 [[50 -2 -7]
 [44 15  8]
 [62  8 35]]
Determinant value for current component: 29184.0
A^T * A after 2th column change: 
 [[ 39  50  -7   9]
 [ -2  44   8  -2]
 [ -7  62  35 -13]
 [  9 -10 -13   6]]

 A^T * A aft

In [ ]:
import math

# Функція для обчислення значення f(x)
def f(x):
    return 2 * math.exp(x) - 3 * x - 2.5

# Похідна f(x) для методу Ньютона
def f_prime(x):
    return 2 * math.exp(x) - 3

# Метод січних
def secant_method(x0, x1, epsilon, max_iter):
    print("Метод січних")
    for i in range(max_iter):
        f_x0 = f(x0)
        f_x1 = f(x1)
        x2 = x1 - f_x1 * (x1 - x0) / (f_x1 - f_x0)
        
        # Вивід результатів ітерації
        print(f"Ітерація {i+1}: x = {x2}, f(x) = {f(x2)}")
        
        # Перевірка на точність
        if abs(x2 - x1) < epsilon:
            print(f"Корінь знайдено з точністю {epsilon}: x = {x2}")
            return x2
        
        x0 = x1
        x1 = x2

    print("Максимальна кількість ітерацій досягнута")
    return x2

def f_double_prime(x):
    return 2 * math.exp(x)

def combined_method(a, b, epsilon, max_iter=10):
    print("Комбінований метод")
    
    x = a  # Початкове значення для методу дотичних
    z0, z1 = a, b  # Початкові значення для методу січних
    
    ep = 1  # Початкова похибка
    n = 0  # Лічильник ітерацій
    
    # Перевірка умови збіжності
    if f_double_prime(x) * f(x) > 0:
        print("Умова збіжності виконана.")
    else:
        print("Умова збіжності не виконана.")
        return None
    
    print(f"n = {n}, x = {x}, z1 = {z1}, Δx = {ep}")
    
    # Ітерації комбінованого методу
    while ep > 2*epsilon and n < max_iter:
        # Метод січних
        z1 = z1 - f(z1) * (z0 - z1) / (f(z0) - f(z1))
        
        # Метод дотичних (Ньютона)
        x = x - f(x) / f_prime(x)
        
        # Обчислення похибки
        ep = abs(z1 - x)
        
        # Підготовка до наступної ітерації
        z0 = x
        n += 1
        
        # Вивід результатів ітерації
        print(f"n = {n}, x1 = {x:.5f}, x2 = {z1:.5f}, x = {((x + z1) / 2):.5f},   Δx = {ep:.8f}")
    
    print("Обчислення завершено.")
    return (x + z1) / 2 

# Приклад виклику функції
a = 1.0
b = 1.5
epsilon = 0.001
combined_method(a, b, epsilon)


# Параметри
epsilon_values = [0.1, 0.01, 0.001, 1e-6]
approximations = [(-0.8, -0.2), (-10, 0)]

max_iter = 100

# Запуск методів для різних значень точності
for epsilon in epsilon_values:
    print(f"\n=== Точність ε = {epsilon} ===")
    for x0, x1 in approximations:
        print(f"=== Наближення x = {(x0, x1)} ===")
        secant_root = secant_method(x0, x1, epsilon, max_iter)
        combined_root = combined_method(x0, x1, epsilon, max_iter)


Комбінований метод
Умова збіжності не виконана.

=== Точність ε = 0.1 ===
=== Наближення x = (-0.8, -0.2) ===
Метод січних
Ітерація 1: x = -0.34843915134758363, f(x) = -0.04310482592051912
Ітерація 2: x = -0.3775980486087703, f(x) = 0.003806116588209285
Корінь знайдено з точністю 0.1: x = -0.3775980486087703
Комбінований метод
Умова збіжності виконана.
n = 0, x = -0.8, z1 = -0.2, Δx = 1
n = 1, x1 = -0.41993, x2 = -0.34844, x = -0.38418,   Δx = 0.07149045
Обчислення завершено.
=== Наближення x = (-10, 0) ===
Метод січних
Ітерація 1: x = -0.17857084949256968, f(x) = -0.29135786817845055
Ітерація 2: x = -0.42793573841859617, f(x) = 0.08751382040958244
Ітерація 3: x = -0.37033609515346716, f(x) = -0.007987280170033806
Корінь знайдено з точністю 0.1: x = -0.37033609515346716
Комбінований метод
Умова збіжності виконана.
n = 0, x = -10, z1 = 0, Δx = 1
n = 1, x1 = -0.83303, x2 = -0.17857, x = -0.50580,   Δx = 0.65445476
n = 2, x1 = -0.42536, x2 = -0.34296, x = -0.38416,   Δx = 0.08239760
Обчис

In [ ]:
import numpy as np
from numpy.linalg import norm

# Define the ill-conditioned matrix H6
H6 = np.array([
    [1, 1/2, 1/3, 1/4, 1/5, 1/6],
    [1/2, 1/3, 1/4, 1/5, 1/6, 1/7],
    [1/3, 1/4, 1/5, 1/6, 1/7, 1/8],
    [1/4, 1/5, 1/6, 1/7, 1/8, 1/9],
    [1/5, 1/6, 1/7, 1/8, 1/9, 1/10],
    [1/6, 1/7, 1/8, 1/9, 1/10, 1/11]
])

# Define x
x = np.ones(6)

# Step 1: Calculate b = H6 * x
b = np.dot(H6, x)
print(f"Vector b = Ax: \n{b}")
# Compute A^T and A^T * A
A_T = H6.T
print(f"Matrix A^T: \n{A_T}")
ATA = np.dot(A_T, H6)
print(f"Matrix A^T * A: \n{ATA}")
ATb = np.dot(A_T, b)
print(f"Vector A^T * b: \n{ATb}")


# Define the ODE function dx/dt = A^T b - A^T A x
def dx_dt(x, ATA, ATb):
    return ATb - np.dot(ATA, x)

# Adams-Bashforth Method
def adams_bashforth(ATA, ATb, dt=0.01, beta=1e-6, max_steps=2000000):
    x_t = np.zeros(6)  # Initial condition x(0) = 0
    x_prev = x_t.copy()
    step = 0

    # Perform Euler step for initialization
    f_t = dx_dt(x_t, ATA, ATb)
    x_t += dt * f_t
    step += 1

    while step <= max_steps:
        # Calculate f_t+1
        f_t_next = dx_dt(x_t, ATA, ATb)

        # Adams-Bashforth formula: x_t+1 = x_t + dt * (3/2 * f_t_next - 1/2 * f_t)
        x_next = x_t + dt * (3/2 * f_t_next - 1/2 * f_t)

        if step == max_steps:
            return x_next, -1, norm(np.dot(ATA, x_next) - ATb)
        # Stopping criterion
        if norm(np.dot(ATA, x_next) - ATb) < beta:
            return x_next, step, norm(np.dot(ATA, x_next) - ATb)

        # Update for next iteration
        x_prev = x_t
        x_t = x_next
        f_t = f_t_next
        step += 1

# Solve the system
x_solution, steps, criteria_val = adams_bashforth(ATA, ATb)
print(f"Solution x = {x_solution}")
print(f"Converged in {steps} steps" if steps != -1 else "Max steps exceeded without convergence")
print(f"Stopping criteria value {criteria_val}")


Vector b = Ax: 
[2.45       1.59285714 1.21785714 0.99563492 0.84563492 0.73654401]
Matrix A^T: 
[[1.         0.5        0.33333333 0.25       0.2        0.16666667]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1       ]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909]]
Matrix A^T * A: 
[[1.49138889 0.85714286 0.61607143 0.48478836 0.40109127 0.3426912 ]
 [0.85714286 0.51179705 0.375      0.29861111 0.24907407 0.21407828]
 [0.61607143 0.375      0.27742205 0.22222222 0.18611111 0.16043771]
 [0.48478836 0.29861111 0.22222222 0.17865662 0.15       0.12954545]
 [0.40109127 0.24907407 0.18611111 0.15       0.12615662 0.10909091]
 [0.3426912  0.21407828 0.16043771 0.12954545 0.10909091 0.09442108]]
Vector A^T * b: 
[4.193174   2.50570338 1.83726452 1.463

In [4]:
print(f"Solution x: \n {x_solution[:, None]}")

Solution x: 
 [[1.00293803]
 [0.97318895]
 [1.029234  ]
 [1.02963114]
 [1.000554  ]
 [0.95915167]]


In [14]:
beta = 0.01
beta_2 = 0.0055
b1 = b + beta
b2 = b + beta_2

ATb1 = np.dot(A_T, b1)

x_b1_solution, steps, criteria_val = adams_bashforth(ATA, ATb1)
print(f"Solution x for b1: \n {x_b1_solution[:, None]}")
print(f"Converged in {steps} steps" if steps != -1 else "Max steps exceeded without convergence")
print(f"Stopping criteria value {criteria_val}")


Solution x for b1: 
 [[1.02982978]
 [0.85981777]
 [1.00244623]
 [1.0733581 ]
 [1.09051567]
 [1.07818396]]
Converged in 1871142 steps
Stopping criteria value 9.999994898656237e-07


In [15]:
ATb2 = np.dot(A_T, b2)

x_b2_solution, steps, criteria_val = adams_bashforth(ATA, ATb2)
print(f"Solution x for b2: \n {x_b2_solution[:, None]}")
print(f"Converged in {steps} steps" if steps != -1 else "Max steps exceeded without convergence")
print(f"Stopping criteria value {criteria_val}")


Solution x for b2: 
 [[1.0177225 ]
 [0.91078938]
 [1.01462683]
 [1.05375553]
 [1.04999559]
 [1.0244706 ]]
Converged in 1776449 steps
Stopping criteria value 9.999993321652367e-07


In [16]:
orig_x_norm = np.linalg.norm(x)
err_0 = np.linalg.norm(x - x_solution) / orig_x_norm
err_1 = np.linalg.norm(x - x_b1_solution) / orig_x_norm
err_2 = np.linalg.norm(x - x_b2_solution) / orig_x_norm

print("Percentage Error for solving using original vector b: {}".format(err_0 * 100))
print("Percentage Error for solving using vector b + 0.01: {}".format(err_1 * 100))
print("Percentage Error for solving using vector b + 0.0055: {}".format(err_2 * 100))

Percentage Error for solving using original vector b: 2.623289434300295
Percentage Error for solving using vector b + 0.01: 8.188822436755439
Percentage Error for solving using vector b + 0.0055: 4.911651571121093


In [17]:
print(f"Vector b1 (b + 0.01): \n {b1[:, None]}")
print(f"Vector b2 (b + 0.0055): \n {b2[:, None]}")


Vector b1 (b + 0.01): 
 [[2.46      ]
 [1.60285714]
 [1.22785714]
 [1.00563492]
 [0.85563492]
 [0.74654401]]
Vector b2 (b + 0.0055): 
 [[2.4555    ]
 [1.59835714]
 [1.22335714]
 [1.00113492]
 [0.85113492]
 [0.74204401]]


In [18]:
print(f"b1 & b norm (b1 = b + 0.01) {np.linalg.norm(b-b1)}")
print(f"b2 & b norm (b2 = b + 0.0055) {np.linalg.norm(b-b2)}")

b1 & b norm (b1 = b + 0.01) 0.024494897427831713
b2 & b norm (b2 = b + 0.0055) 0.013472193585307537
