In [12]:
import numpy as np
from sympy import symbols, simplify, lambdify

# Дані для інтерполяції
x_nodes = np.array([1.0, 1.8, 2.6, 3.4, 4.2])
y_nodes = np.array([1.750, 4.290, 16.446, 48.073, 106.175])
x_values = [1.4, 2.2, 3.0, 3.8]

# Встановлення точності для друку
np.set_printoptions(precision=3, suppress=True)

# 1. Побудова матриці Вандермонда
vandermonde_matrix = np.vander(x_nodes, increasing=True)
print("Матриця Вандермонда:")
print(vandermonde_matrix)

print("Визначник матриці Вандермонда:")
print(f"{np.linalg.det(vandermonde_matrix):.3f}")

# Розв'язання системи лінійних рівнянь
coefficients = np.linalg.solve(vandermonde_matrix, y_nodes)

# Round coefficients to 4 decimal places
coefficients = np.round(coefficients, 3)
print("\nКоефіцієнти канонічного полінома:")
print(coefficients)

# Формування канонічного полінома
x = symbols('x')
canonical_polynomial = sum(c * x**i for i, c in enumerate(coefficients))
canonical_polynomial = simplify(canonical_polynomial)
print("\nКанонічний інтерполяційний поліном:")
print(canonical_polynomial)

# Function to evaluate the canonical polynomial
canonical_polynomial_func = lambdify(x, canonical_polynomial)

# 2. Використання полінома Лагранжа максимального степеня
def lagrange_polynomial(x_nodes, y_nodes, x_val):
    n = len(x_nodes)
    result = 0
    for i in range(n):
        li = 1
        for j in range(n):
            if j != i:
                li *= (x_val - x_nodes[j]) / (x_nodes[i] - x_nodes[j])
        result += li * y_nodes[i]
    return result

print("\nЗначення P(x) за поліномом Лагранжа максимального степеня:")
for x_val in x_values:
    lagrange_result = lagrange_polynomial(x_nodes, y_nodes, x_val)
    print(f"P({x_val}) = {lagrange_result:.3f}")

# 3. Поліном Лагранжа другого степеня
def lagrange_second_degree(x_nodes, y_nodes, x_val):
    # Знаходимо три найближчі вузли до x_val
    distances = np.abs(x_nodes - x_val)
    sorted_indices = np.argsort(distances)[:3]
    selected_x = x_nodes[sorted_indices]
    selected_y = y_nodes[sorted_indices]

    # Обчислення полінома Лагранжа другого степеня
    return lagrange_polynomial(selected_x, selected_y, x_val)

print("\nЗначення P(x) за поліномом Лагранжа другого степеня:")
for x_val in x_values:
    lagrange_result = lagrange_second_degree(x_nodes, y_nodes, x_val)
    print(f"P({x_val}) = {lagrange_result:.3f}")

# Evaluate and print the values for all x_nodes and x_values
print("\nЗначення поліномів для всіх x_nodes та x_values:")

for x_val in np.concatenate((x_nodes, x_values)):
    canonical_val = canonical_polynomial_func(x_val)
    lagrange_max_deg_val = lagrange_polynomial(x_nodes, y_nodes, x_val)
    lagrange_second_deg_val = lagrange_second_degree(x_nodes, y_nodes, x_val)
    print(f"x = {x_val}: Canonical = {canonical_val:.3f}, Lagrange (Max Degree) = {lagrange_max_deg_val:.3f}, Lagrange (Second Degree) = {lagrange_second_deg_val:.3f}")


Матриця Вандермонда:
[[  1.      1.      1.      1.      1.   ]
 [  1.      1.8     3.24    5.832  10.498]
 [  1.      2.6     6.76   17.576  45.698]
 [  1.      3.4    11.56   39.304 133.634]
 [  1.      4.2    17.64   74.088 311.17 ]]
Визначник матриці Вандермонда:
30.924

Коефіцієнти канонічного полінома:
[ -7.531  21.579 -17.769   5.76   -0.29 ]

Канонічний інтерполяційний поліном:
-0.29*x**4 + 5.76*x**3 - 17.769*x**2 + 21.579*x - 7.531

Значення P(x) за поліномом Лагранжа максимального степеня:
P(1.4) = 2.545
P(2.2) = 8.483
P(3.0) = 29.321
P(3.8) = 73.488

Значення P(x) за поліномом Лагранжа другого степеня:
P(1.4) = 1.818
P(2.2) = 7.934
P(3.0) = 29.826
P(3.8) = 73.815

Значення поліномів для всіх x_nodes та x_values:
x = 1.0: Canonical = 1.749, Lagrange (Max Degree) = 1.750, Lagrange (Second Degree) = 1.750
x = 1.8: Canonical = 4.288, Lagrange (Max Degree) = 4.290, Lagrange (Second Degree) = 4.290
x = 2.6: Canonical = 16.441, Lagrange (Max Degree) = 16.446, Lagrange (Second Degre